### ISSUE TITLE
[GUI] Crash adjusting near/far

### ISSUE THREAD

**Issue by MephestoKhaan** [openpool/openpool-core-unity#5]
When calibrating the table, making the resh far bigger than the near crashes the GUI application.
Windows 8.1

**Comment by MephestoKhaan** [comment]
For some reason today it's working, I did nothing so could be due to my drivers updating

**Comment by zedle** [comment]
yea i'm getting this same issue

**Comment by los93sol** [comment]
Could one of you please advise how you resolved the missing meta files in the repo?
